### ISSUE TITLE
Game crash when shulker box is placed next to a frame

### ISSUE THREAD

**Issue by MJRamon** [starfish-studios/Building-But-Better#6]
Minecraft 1.20.1, Building But Better 1.0.2

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-07-18 02:25:33
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "$$1" is null
at net.minecraft.class_2480.method_25959(class_2480.java:243)
at net.minecraft.class_4970$class_4971.method_26222(class_4970.java:1047)
at net.minecraft.class_5431$1.method_30367(class_5431.java:15)
at net.minecraft.class_4970$class_4971.method_30368(class_4970.java:1241)
at net.minecraft.class_4970$class_4971.method_26206(class_4970.java:1234)
at com.starfish_studios.bbb.block.FrameBlock.validConnection(FrameBlock.java:214)
at com.starfish_studios.bbb.block.FrameBlock.getConnections(FrameBlock.java:163)
at com.starfish_studios.bbb.block.FrameBlock.method_9559(FrameBlock.java:134)
at net.minecraft.class_4970$class_4971.mixinextras$bridge$method_9559$140(class_4970.java)
at net.minecraft.class_4970$class_4971.wrapOperation$kpm000$wilderwild$wilderWild$updateShape(class_4970.java:7023)
at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:1149)
at net.minecraft.class_7165.method_42393(class_7165.java:36)
at net.minecraft.class_7159$class_7272.method_41707(class_7159.java:143)
at net.minecraft.class_7159.method_41702(class_7159.java:78)
at net.minecraft.class_7159.method_41706(class_7159.java:65)
at net.minecraft.class_7159.method_42392(class_7159.java:32)
at net.minecraft.class_1937.method_42308(class_1937.java:344)
at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:1092)
at net.minecraft.class_1937.method_30092(class_1937.java:256)
at net.minecraft.class_638.method_30092(class_638.java:157)
at net.minecraft.class_1937.method_8652(class_1937.java:213)
at net.minecraft.class_1747.method_7708(class_1747.java:163)
at net.minecraft.class_1747.method_7712(class_1747.java:80)
at net.minecraft.class_1747.method_7884(class_1747.java:50)
at net.minecraft.class_1799.method_7981(class_1799.java:272)
at net.minecraft.class_636.method_41934(class_636.java:366)
at net.minecraft.class_636.method_41933(class_636.java:324)
at net.minecraft.class_636.method_41931(class_636.java:278)
at net.minecraft.class_636.method_2896(class_636.java:323)
at net.minecraft.class_310.method_1583(class_310.java:1802)
at net.minecraft.class_310.redirect$bel000$betterthirdperson$onDoItemUse(class_310.java:11096)
at net.minecraft.class_310.method_1508(class_310.java:2052)
at net.minecraft.class_310.method_1574(class_310.java:1883)
at net.minecraft.class_310.method_1523(class_310.java:1181)
at net.minecraft.class_310.method_1514(class_310.java:802)
at net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at net.minecraft.class_2480.method_25959(class_2480.java:243)
at net.minecraft.class_4970$class_4971.method_26222(class_4970.java:1047)
at net.minecraft.class_5431$1.method_30367(class_5431.java:15)
at net.minecraft.class_4970$class_4971.method_30368(class_4970.java:1241)
at net.minecraft.class_4970$class_4971.method_26206(class_4970.java:1234)
at com.starfish_studios.bbb.block.FrameBlock.validConnection(FrameBlock.java:214)
at com.starfish_studios.bbb.block.FrameBlock.getConnections(FrameBlock.java:163)
at com.starfish_studios.bbb.block.FrameBlock.method_9559(FrameBlock.java:134)
at net.minecraft.class_4970$class_4971.mixinextras$bridge$method_9559$140(class_4970.java)
at net.minecraft.class_4970$class_4971.wrapOperation$kpm000$wilderwild$wilderWild$updateShape(class_4970.java:7023)
at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:1149)
at net.minecraft.class_7165.method_42393(class_7165.java:36)
at net.minecraft.class_7159$class_7272.method_41707(class_7159.java:143)
at net.minecraft.class_7159.method_41702(class_7159.java:78)
at net.minecraft.class_7159.method_41706(class_7159.java:65)
at net.minecraft.class_7159.method_42392(class_7159.java:32)
at net.minecraft.class_1937.method_42308(class_1937.java:344)
at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:1092)
at net.minecraft.class_1937.method_30092(class_1937.java:256)
at net.minecraft.class_638.method_30092(class_638.java:157)
at net.minecraft.class_1937.method_8652(class_1937.java:213)
at net.minecraft.class_1747.method_7708(class_1747.java:163)
at net.minecraft.class_1747.method_7712(class_1747.java:80)
at net.minecraft.class_1747.method_7884(class_1747.java:50)
at net.minecraft.class_1799.method_7981(class_1799.java:272)
at net.minecraft.class_636.method_41934(class_636.java:366)
at net.minecraft.class_636.method_41933(class_636.java:324)
at net.minecraft.class_636.method_41931(class_636.java:278)
at net.minecraft.class_636.method_2896(class_636.java:323)
at net.minecraft.class_310.method_1583(class_310.java:1802)
at net.minecraft.class_310.redirect$bel000$betterthirdperson$onDoItemUse(class_310.java:11096)
at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
All players: 2 total; [class_746['TwoRog'/513450, l='ClientLevel', x=-38.64, y=68.00, z=40.11], class_745['NivoRAZH'/943095, l='ClientLevel', x=30.01, y=61.00, z=23.02]]
Chunk stats: 1024, 263
Level dimension: minecraft:overworld
Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Level time: 17919190 game time, 4181540 day time
Server brand: fabric
Server type: Non-integrated multiplayer server
```

**Comment by crispytwig** [comment]
This has been fixed and will shortly be available.

https://github.com/starfish-studios/Building-But-Better/commit/299cde66f04c5154dd470909e42d63bfea13178b
