### ISSUE TITLE
Crash when using chisel and bit block near any item of Building but better

### ISSUE THREAD

**Issue by djdado16** [starfish-studios/Building-But-Better#9]
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.BlockGetter.m_7702_(net.minecraft.core.BlockPos)" because "worldIn" is null
	at mod.chiselsandbits.block.ChiseledBlock.getBlockEntity(ChiseledBlock.java:223) ~[chisels-and-bits-forge-1.4.148.jar%23355!/:1.4.148]
	at mod.chiselsandbits.block.ChiseledBlock.m_7947_(ChiseledBlock.java:324) ~[chisels-and-bits-forge-1.4.148.jar%23355!/:1.4.148]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60816_(MixinBlockStateBase.java:688) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.block.SupportType$1.m_5588_(SupportType.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60659_(MixinBlockStateBase.java:880) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60783_(MixinBlockStateBase.java:876) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at com.starfish_studios.bbb.block.FrameBlock.validConnection(FrameBlock.java:212) ~[bbb-1.20.1-forge-1.0.1.jar%23301!/:1.20.1-forge-1.0.1]
	at com.starfish_studios.bbb.block.FrameBlock.getConnections(FrameBlock.java:164) ~[bbb-1.20.1-forge-1.0.1.jar%23301!/:1.20.1-forge-1.0.1]
	at com.starfish_studios.bbb.block.FrameBlock.m_7417_(FrameBlock.java:132) ~[bbb-1.20.1-forge-1.0.1.jar%23301!/:1.20.1-forge-1.0.1]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60728_(MixinBlockStateBase.java:794) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.redstone.NeighborUpdater.m_230770_(NeighborUpdater.java:36) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$ShapeUpdate.m_213563_(CollectingNeighborUpdater.java:143) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230645_(CollectingNeighborUpdater.java:78) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230660_(CollectingNeighborUpdater.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_213547_(CollectingNeighborUpdater.java:32) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.Level.m_213683_(Level.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60705_(MixinBlockStateBase.java:736) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:260) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:68) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.ItemStack.lambda$useOn$3(ItemStack.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:339) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.redirect$hcm000$onDoItemUse(Minecraft.java:16973) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23986!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by playwmadness** [comment]
```
net.minecraft.world.level.BlockGetter.m_7702_(net.minecraft.core.BlockPos)" because "worldIn" is null
...
at com.starfish_studios.bbb.block.FrameBlock.validConnection(FrameBlock.java:212)
at com.starfish_studios.bbb.block.FrameBlock.getConnections(FrameBlock.java:164)
...
```

Seems related to #6 and is fixed by #7
